### PR TITLE
Support of SELECT DISTINCT and GROUP BY

### PR DESCRIPTION
**Pull request by walter-weinmann**
Support of SELECT DISTINCT and GROUP BY regarding distinct result columns in the SELECT clause.

### CODE REVIEW

**Comment by walter-weinmann** [comment]
It is not yet defined how the red and blue marked values in the case of duplicate rows should be treated:

image

**Comment by acautin** [comment]
@walter-weinmann I don't understand so well why you need to filter some of the rows, can you explain a little how you implemented the aggregation?, shouldn't imem have filter the unwanted rows already ?

**Comment by walter-weinmann** [comment]
In dderl the duplicate rows have also to be ignored.

**Comment by acautin** [comment]
@walter-weinmann wouldn't it be possible to filter them on imem and only send the aggregated resulting data ?

**Pull request closed without merging**
