### PR TITLE
removed unused files.

### LINKED ISSUE #101: DDErl priv cleanup
Remove ?
---
priv/d3.html
priv/griddlg.html
priv/group.html
priv/slick.html
priv/sql_test.html
priv/test.html
priv/touch.html
priv/vectgraph.html
priv/templates/*

Others (`priv/static`)
---
success.mp3 (duplicate priv/static/media/success.mp3)

Is priv/static/tests used/required?

Can JQ and other 3rd party libraries moved to: priv/lib? JQ(and JQUI) are now in priv/static/scripts with dderl scripts

css-s are also should be reorganized as ours and third party/lib etc.

### PR DESCRIPTION
**Pull request by acautin**
Deleted unused files and removed angularjs dependency. Fixes #101

### CODE REVIEW

**Comment by acautin** [comment]
Hello @c-bik , if you haven't finished the build yet and you think it is not too risky you can merge this pr with the cleanup / removal of deps.

**Comment by c-bik** [comment]
@acautin Haven't build yet still collecting bugs. Can it break anything in DDErl? Can I just merge without verifying?

**Comment by acautin** [comment]
@c-bik  Better wait then until it can be properly tested.

**Comment by c-bik** [comment]
@acautin Do we now have to use brunch with DDErl too?

**Comment by acautin** [comment]
@c-bik not yet, that is still on the branch https://github.com/K2InformaticsGmbH/dderl/tree/bower_and_updated_deps

**Comment by c-bik** [comment]
@acautin is there an issue tracking it?

**Comment by acautin** [comment]
Part of #100 y will modify it :+1:

**Pull request merged**
