### PR TITLE
CSV Ctrl+C/V enhancements

### LINKED ISSUE #361: Personalized csv export preferences
The currently available ddConfig options for csv export 
* [{dderl,gen_adapter,csvExportDelimiter}]	";"
* [{dderl,gen_adapter,csvExportDelimiterNewLine}]	"\n"

should be extended by
* [{dderl,gen_adapter,csvExportEncoding}]	utf8
* [{dderl,gen_adapter,csvExportBomPrefix}]	<<>>

and generalized in the sense that the user id is part of the context.

Also, the escaping must include the chosen field separator.

Open discussion: when do we need to escape the " character

### PR DESCRIPTION
**Pull request by c-bik**
Fixes #361 
image
[`encoding_to_bom(InEncoding)`](http://erlang.org/doc/man/unicode.html#encoding_to_bom-1) is used to internally get the bytes array of character encoding (`[{dderl,gen_adapter,csvExportBomPrefix}]`) instead of configurable byte array.

### CODE REVIEW

**Comment by acautin** [comment]
@stoch did you have a chance to look into this ?, we should merge soon to avoid running into conflicts later.

**Comment by stoch** [comment]
@acautin  This was discussed yesterday with @c-bik who should take the lead for the finalisation.

**Comment by stoch** [comment]
@c-bik Please do not touch copy or paste code for Editors. They will always go in and out unescaped.

**Comment by c-bik** [comment]
@acautin Ctrl+C/V requires one more modification (discussed with @stoch yesterday) - " wrapping only if contains \n \r or \t
In a few days I should be able to add one more (and final) commit to this PR

**Comment by c-bik** [comment]
> @c-bik Please do not touch copy or paste code for Editors. They will always go in and out unescaped.

Ctrl+C is common. What is copy/paste for editor?

**Comment by c-bik** [comment]
`""` (double double-quote wrapping an empty string) and `"` (single double-quote, unbalanced) are not handled to keep the implementation simple

I don't think these two cases have any impact on any valid usecases

**Pull request merged**
