### PR TITLE
Histogram with multiple columns - complete version.

### PR DESCRIPTION
**Pull request by walter-weinmann**
Sorry - I can't manage to separate the modification of the script.

### CODE REVIEW

**Comment by walter-weinmann** [comment]
I think the title of the histogram window should not contain the column names. This is redundant (see the column header) and therefore the title should simply be 'Histogram'.

**Comment by stoch** [comment]
@walter-weinmann Thanks for this. We are busy tomorrow with an installation but can probably integrate this after tomorrow.
Maybe we would like to have one column per grouping attribute in the future. Also the sorting on the GUI side was not too comfortable back in the old days. Will check in your version and give feedback soon.

**Comment by c-bik** [comment]
@walter-weinmann Its ok with the script quote removal though its not related it can still part of this PR as its too trivial

Can you please paste some screen-shots here to give an idea of how its looks in with your PR?

**Comment by walter-weinmann** [comment]
I agree with the sorting which is very unfortunate for numeric values. I'm
not sure about the usage of the histogram - but I think a descending
default sort with count would be appropriate.

Having one column per grouping attribute is much more effort implementation
wise and I'm not quite sure about the advantage for the user.

On 26 January 2016 at 20:52, Stefan Ochsenbein <notifications@github.com>
wrote:

> @walter-weinmann <https://github.com/walter-weinmann> Thanks for this. We
> are busy tomorrow with an installation but can probably integrate this
> after tomorrow.
> Maybe we would like to have one column per grouping attribute in the
> future. Also the sorting on the GUI side was not too comfortable back in
> the old days. Will check in your version and give feedback soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/K2InformaticsGmbH/dderl/pull/154#issuecomment-175198442>
> .
>



-- 

___________________________________________________________________________
*Walter Weinmann*
___________________________________________________________________________
Obertorplatz 4
CH-4130 Rheinfelden
Tel +41 (0)61 841 06 10
___________________________________________________________________________
Schulstrasse 1
CH-6037 Root
Tel +41 (0)41 530 39 70
___________________________________________________________________________

**Comment by walter-weinmann** [comment]
[image: Inline images 1]

[image: Inline images 2]




On 26 January 2016 at 20:58, Bikram Chatterjee <notifications@github.com>
wrote:

> @walter-weinmann <https://github.com/walter-weinmann> Its ok with the
> script quote removal though its not related it can still part of this PR as
> its too trivial
>
> Can you please paste some screen-shots here to give an idea of how its
> looks in with your PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/K2InformaticsGmbH/dderl/pull/154#issuecomment-175201074>
> .
>



-- 

___________________________________________________________________________
*Walter Weinmann*
___________________________________________________________________________
Obertorplatz 4
CH-4130 Rheinfelden
Tel +41 (0)61 841 06 10
___________________________________________________________________________
Schulstrasse 1
CH-6037 Root
Tel +41 (0)41 530 39 70
___________________________________________________________________________

**Comment by c-bik** [comment]
Git couldn't handle image through mail...
image

**Comment by walter-weinmann** [comment]
Should be ok now.

On 26 January 2016 at 21:28, Bikram Chatterjee <notifications@github.com>
wrote:

> Git couldn't handle image through mail...
> [image: image]
> <https://cloud.githubusercontent.com/assets/913008/12593900/aa37af4a-c473-11e5-94f5-e7ac7b4209a3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/K2InformaticsGmbH/dderl/pull/154#issuecomment-175210792>
> .
>



-- 

___________________________________________________________________________
*Walter Weinmann*
___________________________________________________________________________
Obertorplatz 4
CH-4130 Rheinfelden
Tel +41 (0)61 841 06 10
___________________________________________________________________________
Schulstrasse 1
CH-6037 Root
Tel +41 (0)41 530 39 70
___________________________________________________________________________

**Comment by c-bik** [comment]
Somehow images are still not rendering in my browser. I, however, could follow the links and see them. Re-posting for anyone else having the same problem.

Thanks @walter-weinmann 

image
and
image

cc @stoch if you have any comments on look-n-feel

**Comment by walter-weinmann** [comment]
I think the _showHistogram function should be simplified. Instead of

```javascript
    _showHistogram: function(data) {
        var self = this;
        var columnId = data.columnId;
        console.log('show histogram ' + JSON.stringify(data));

        var title = '';
        var _separator = '';
        for(var c = 0; c < columnId.length; ++c) {
           for(var colId in self._origcolumns) {
                if(self._origcolumns[colId] === columnId[c]) {
                    var columns = self._grid.getColumns();
                    for(var i = 0; i < columns.length; ++i) {
                        if(columns[i].field === colId) {
                            title += _separator + columns[i].name;
                            _separator = ' | ';
                            console.log(columns[i].name);
                            break;
                        }
                    }
                    break;
                }
            }
        }
        $('<div>').appendTo(document.body)
            .statsTable({
                title          : title + " histogram",
                initialQuery   : self._cmd,
                columnIds      : columnId,
                dderlStatement : self._stmt,
                parent         : self._dlg
            })
            .statsTable('load', 'histogram');
    },
```

we should have:

```javascript
    _showHistogram: function(data) {
        var self = this;
        var columnId = data.columnId;
        console.log('show histogram ' + JSON.stringify(data));

        $('<div>').appendTo(document.body)
            .statsTable({
                title          : 'Histogram',
                initialQuery   : self._cmd,
                columnIds      : columnId,
                dderlStatement : self._stmt,
                parent         : self._dlg
            })
            .statsTable('load', 'histogram');
    },
```

Now the result looks as follows:



We could also choose a different separator character for the histogram columns.

And finally the default sorting could be first count descending and second the combined histogram columns ascending.

**Comment by walter-weinmann** [comment]
Here are two examples with the suggested default sort:



and


The code changes in module dderl_fsm function handle_sync_event:

```erlang
    ?Debug("Histo Rows ~p", [Result]),
    HistoRows = [[nop, Value, integer_to_binary(Count), 100 * Count / Total] || {Value, Count} <- Result],
    SortFun = fun(X,Y) ->
        X2 = lists:nth(2,X),
        Y2 = lists:nth(2,Y),
        X3 = lists:nth(3,X),
        Y3 = lists:nth(3,Y),
        if
            X3 > Y3 -> true;
            X3 < Y3 -> false;
            X2 > Y2 -> false;
            true -> true
        end
    end,
    HistoRowsSort = lists:sort(SortFun,HistoRows),
    HistoRowsWithId = [[Idx | lists:nth(Idx, HistoRowsSort)] || Idx <- lists:seq(1, length(HistoRowsSort))],
```

**Pull request closed without merging**
